# Generated by Django 5.2.17 on 2026-10-02 05:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='학명')),
                ('authorship', models.CharField(blank=True, help_text='예: (Doyère, 1840)', max_length=200, verbose_name='명명자')),
                ('rank', models.CharField(choices=[('phylum', '문'), ('class', '강'), ('order', '목'), ('superfamily', '상과'), ('family', '과'), ('subfamily', '아과'), ('genus', '속'), ('species', '종'), ('subspecies', '아종')], default='species', max_length=20, verbose_name='계급')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='occurrences.taxon', verbose_name='상위 분류군')),
            ],
            options={
                'verbose_name': '분류군',
                'verbose_name_plural': '분류군',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='위도')),
                ('decimal_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='경도')),
                ('coordinate_uncertainty_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='좌표 불확도(m)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='나라')),
                ('locality', models.CharField(blank=True, max_length=300, verbose_name='산지')),
                ('habitat', models.CharField(blank=True, help_text='예: 이끼, 지의류, 담수 퇴적물, 해양 간극', max_length=200, verbose_name='서식지')),
                ('elevation_m', models.IntegerField(blank=True, null=True, verbose_name='고도(m)')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='채집일')),
                ('recorded_by', models.CharField(blank=True, max_length=200, verbose_name='채집자')),
                ('basis_of_record', models.CharField(choices=[('PreservedSpecimen', '표본'), ('MaterialSample', '시료'), ('HumanObservation', '관찰'), ('MaterialCitation', '문헌 기록')], default='PreservedSpecimen', max_length=30, verbose_name='기록 근거')),
                ('reference', models.TextField(blank=True, verbose_name='출처 문헌')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생긴 때')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='고친 때')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='occurrences.taxon', verbose_name='분류군')),
            ],
            options={
                'verbose_name': '산출',
                'verbose_name_plural': '산출',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(fields=('scientific_name', 'rank'), name='uniq_taxon_name_rank'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['decimal_latitude', 'decimal_longitude'], name='occurrences_decimal_5ab7f1_idx'),
        ),
    ]
