# Generated by Django 5.2.16 on 2026-10-02 06:34

import django.db.models.deletion
import occurrences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=occurrences.models.photo_path, verbose_name='사진')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=occurrences.models.thumbnail_path, verbose_name='섬네일')),
                ('description', models.CharField(blank=True, help_text='예: 배면, 광학현미경 ×400', max_length=300, verbose_name='설명')),
                ('creator', models.CharField(blank=True, max_length=200, verbose_name='찍은 이')),
                ('license', models.CharField(blank=True, help_text='예: CC BY 4.0', max_length=100, verbose_name='이용 허락')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='올린 때')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='occurrences.occurrence', verbose_name='산출')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
                'ordering': ['id'],
            },
        ),
    ]
