# Generated by Django 5.2.16 on 2026-10-03 05:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, help_text='정확한 날짜를 아는 경우만 입력한다. 일부만 알려진 날짜는 채집일 원문에 남긴다.', null=True, verbose_name='채집일')),
                ('event_date_verbatim', models.CharField(blank=True, help_text='예: 1998년, 2025년 5~6월. 정확한 날짜를 모르면 채집일은 비우고 여기에 적는다.', max_length=200, verbose_name='채집일 원문')),
                ('recorded_by', models.CharField(blank=True, max_length=200, verbose_name='채집자')),
                ('sampling_protocol', models.TextField(blank=True, verbose_name='채집 방법')),
                ('sampling_effort', models.CharField(blank=True, help_text='예: 30분, 따개비 10개, 이끼 10 g. 단위를 함께 적는다.', max_length=200, verbose_name='채집 노력량')),
                ('reference', models.TextField(blank=True, verbose_name='출처 문헌')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '채집',
                'verbose_name_plural': '채집',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='채집지 이름')),
                ('locality', models.CharField(blank=True, max_length=300, verbose_name='산지 상세')),
                ('decimal_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='위도')),
                ('decimal_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='경도')),
                ('coordinate_uncertainty_m', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='좌표 불확도(m)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='나라')),
                ('realm', models.CharField(choices=[('marine', '해양'), ('terrestrial', '육상'), ('freshwater', '담수'), ('unknown', '미지정')], default='unknown', max_length=20, verbose_name='환경 구분')),
                ('habitat', models.CharField(blank=True, max_length=200, verbose_name='서식지')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '채집지',
                'verbose_name_plural': '채집지',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='identification_qualifier',
            field=models.CharField(blank=True, help_text='예: cf., aff., sp.', max_length=100, verbose_name='동정 한정어'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='identified_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='동정자'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='individual_count',
            field=models.PositiveIntegerField(blank=True, help_text='확인한 개체 수(1 이상). 미계수는 비워 둔다. 미산출·부재는 이 칸으로 기록하지 않는다.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='개체 수'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='decimal_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='decimal_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='occurrences.occurrence', verbose_name='산출'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(help_text='연구실에서 쓰는 표본·시료 번호. 한 채집 안에서 중복되지 않게 적는다.', max_length=100, verbose_name='시료 번호')),
                ('substrate', models.CharField(blank=True, help_text='예: 따개비, 이끼, 모래', max_length=200, verbose_name='채집 기질')),
                ('host_taxon', models.CharField(blank=True, help_text='예: 채집한 따개비의 학명. 완보동물 학명은 산출에 적는다.', max_length=200, verbose_name='숙주·기질 생물 학명')),
                ('description', models.TextField(blank=True, verbose_name='시료 설명')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='occurrences.collectionevent', verbose_name='채집')),
            ],
            options={
                'verbose_name': '시료',
                'verbose_name_plural': '시료',
                'ordering': ['sample_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='sample',
            field=models.ForeignKey(blank=True, help_text='시료를 연결하면 산지·좌표·채집일·채집자는 해당 채집의 정보를 사용한다.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='occurrences.sample', verbose_name='시료'),
        ),
        migrations.AddField(
            model_name='photo',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='occurrences.sample', verbose_name='시료'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(('sample__isnull', False), models.Q(('decimal_latitude__isnull', False), ('decimal_longitude__isnull', False)), _connector='OR'), name='occurrence_sample_or_coordinates'),
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='occurrences.site', verbose_name='채집지'),
        ),
        migrations.AddField(
            model_name='photo',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='occurrences.site', verbose_name='채집지'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('occurrence__isnull', False), ('sample__isnull', True), ('site__isnull', True)), models.Q(('occurrence__isnull', True), ('sample__isnull', True), ('site__isnull', False)), models.Q(('occurrence__isnull', True), ('sample__isnull', False), ('site__isnull', True)), _connector='OR'), name='photo_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('event', 'sample_code'), name='uniq_sample_code_event'),
        ),
    ]
